shop/urls.py
from magicepic_website.settings import MEDIA_ROOT
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('store/', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('resetpassword_validate/<uidb64>/<token>', views.resetpassword_validate, name='resetpassword_validate'),
    path('store/search/', views.search, name='search'),
    path('add_cart/<int:product_id>', views.add_cart, name='add_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
    path('store/category/<slug:category_slug>', views.store, name='products_by_category'),
    path('store/category/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.db.models.aggregates import Variance
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=100, unique = True)
    slug = models.SlugField(max_length=1000, unique = True)
    description = models.TextField(max_length = 2000, blank=True)
    category_image = models.ImageField(upload_to='photos/categories/')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('products_by_category', args=[self.slug])

    def __str__(self):
        return self.category_name

class AccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("User must have an email address")

        if not username:
            raise ValueError("User must have an username")

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password= password,
            first_name = first_name,
            last_name = last_name,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user
    


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique = True)
    email = models.EmailField(max_length=50, unique = True)
    phone_number = models.CharField(max_length=11)
    
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default = False)
    is_staff = models.BooleanField(default = False)
    is_active = models.BooleanField(default = False)
    is_superadmin = models.BooleanField(default = False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name',]
    
    objects = AccountManager()
    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique = True)
    slug = models.SlugField(max_length=1000, unique = True)
    description = models.TextField(max_length = 2000, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products/')
    stock = models.IntegerField() #stock
    is_available = models.BooleanField(default = False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name



class Discount(models.Model):
    promo_code = models.CharField(max_length=200, unique = True)
    date_end = models.DateTimeField()
    percent = models.IntegerField()
    amount = models.IntegerField()
    is_active = models.BooleanField(default = False)

    def __str__(self):
        return self.promo_code

class VariationManager(models.Manager):
    def varient(self): #If needed, more functions will be added. more function = more varient
        return super(VariationManager, self).filter(variation_category='varient', is_active=True)
variation_category_choice = (
    ('varient', 'varient'),
    # ('color', 'color'),
)
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=200, choices=variation_category_choice)
    variation_value = models.CharField(max_length=200)
    # quantity = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default = True)

    def __str__(self):
        return self.variation_value


class Cart(models.Model):
    cart_id = models.CharField(max_length=200, blank = True)
    date_added = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default = True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product


#order

class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE) 
    payment_id = models.CharField(max_length=200)
    payment_method = models.CharField(max_length=200)
    amount_paid = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id

class Cart_Discount_Delivery(models.Model): #for cart discounts and delivery cost
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    delivery_cost = models.IntegerField()
    discount = models.FloatField()


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True) 
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True) 
    order_number = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    address_line_1 = models.CharField(max_length=200)
    address_line_2 = models.CharField(max_length=200)
    district = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    total = models.CharField(max_length=200)
    delivery_cost = models.IntegerField(default=120)
    discount = models.FloatField(default=0)
    status = models.CharField(max_length=200, choices=STATUS, default='New')
    ip = models.CharField(max_length=200)
    order_note = models.CharField(max_length=200)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {} {}'.format(self.order_number, self.first_name, self.last_name)

class OrderProduct(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE) 
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE) 
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)   
    order_number = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    size = models.CharField(max_length=200)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

shop/forms.py
from django import forms
from .models import *

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Enter Password",
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Confirm Password",

    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        #giving all of form a css class  
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password!=confirm_password:
            raise forms.ValidationError("Passwords do not match! Try again.")

class CartDiscountDeliveryForm(forms.ModelForm):
    class Meta:
        model = Cart_Discount_Delivery
        fields = ['delivery_cost', 'discount']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2', 'district', 'city', 'order_note']

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>
      MagicEpic | One of the Biggest Online K-Pop Shopping Platform in
      Bangladesh
    </title>

    <link
      href="{% static 'shop/images/favicon.ico' %}"
      rel="shortcut icon"
      type="image/x-icon"
    />

    <!-- jQuery -->
    <script
      src="{% static 'shop/js/jquery-2.0.0.min.js' %}"
      type="text/javascript"
    ></script>

    <!-- Bootstrap4 files-->
    <script
      src="{% static 'shop/js/bootstrap.bundle.min.js' %}"
      type="text/javascript"
    ></script>
    <link
      href="{% static 'shop/css/bootstrap.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <!-- Font awesome 5 -->
    <link
      href="{% static 'shop/fonts/fontawesome/css/all.min.css' %}"
      type="text/css"
      rel="stylesheet"
    />

    <!-- custom style -->
    <link
      href="{% static 'shop/css/ui.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'shop/css/responsive.css' %}"
      rel="stylesheet"
      media="only screen and (max-width: 1200px)"
    />

    <!-- custom javascript -->
    <script
      src="{% static 'shop/js/script.js' %}"
      type="text/javascript"
    ></script>

    <script type="text/javascript">
      /// some script

      // jquery ready start
      $(document).ready(function () {
        // jQuery code
      });
      // jquery end
    </script>
  </head>
  <body>
  <!-- Messenger Chat Plugin Code -->
  <div id="fb-root"></div>

  <!-- Your Chat Plugin code -->
  <div id="fb-customer-chat" class="fb-customerchat">
  </div>

  <script>
    var chatbox = document.getElementById('fb-customer-chat');
    chatbox.setAttribute("page_id", "103851271505406");
    chatbox.setAttribute("attribution", "biz_inbox");

    window.fbAsyncInit = function() {
      FB.init({
        xfbml            : true,
        version          : 'v12.0'
      });
    };

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  
  
  
    
    <!-- navbar  -->

    {% include 'shop/includes/navbar.html' %}

    {% block content %} {% endblock %}


    <!-- footer  -->

    {% include 'shop/includes/footer.html' %}


  </body>
  </html>

shop/templates/shop/cart.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
    <div class="text-center">
      <h2>Your shopping cart is empty.</h2>
      <br>

      <a href="{% url 'store' %}" class='btn btn-primary'>Start Shopping!</a>
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>
              {% for cart_item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
                    <figcaption class="info">
                      <a href="{{ cart_item.product.get_url }}"
                        class="title text-dark">{{ cart_item.product.product_name }}</a>
                      <p class="text-muted small">
                        {% if cart_item.variations.all %}
                        {% for item in cart_item.variations.all %}
                        {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                        {% endfor %}
                        {% endif %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light"
                          type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                      </div>
                      <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                      <div class="input-group-append">
                        <form action="{% url 'add_cart' cart_item.product.id %}" method="post">
                          {% csrf_token %}
                          {% for item in cart_item.variations.all %}
                          <input type="hidden" name="{{item.variation_category | lower}}"
                            value="{{ item.variation_value | capfirst }}">
                          {% endfor %}
                          <button href="{% url 'add_cart' cart_item.product.id %}" class="btn btn-light" type="submit"
                            id="button-minus"> <i class="fa fa-plus"></i> </button>
                        </form>
                      </div>
                    </div> <!-- input-group.// -->
                  </div> <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">৳{{cart_item.sub_total}} </var>
                    <small class="text-muted"> ৳{{cart_item.product.price}} each </small>
                  </div> <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}"
                    onclick="return confirm('Are you sure you want to remove this item?')" class="btn btn-danger">
                    Remove</a>
                </td>
              </tr>
              {% endfor %}



            </tbody>
          </table>
        </div> <!-- card.// -->
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Location*</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>

              <tr>
                <form action="{% url 'cart' %}" class="location" method='POST'> {% csrf_token %}
                  <td>
                    {% if delivery_cost == 0 %}
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="location" id="inside_dhaka" value="1">
                      <label class="form-check-label" for="exampleRadios1">
                        Inside Dhaka City
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="location" id="outside_dhaka" value="0">
                      <label class="form-check-label" for="exampleRadios2">
                        Outside Dhaka City
                      </label>
                    </div>
                    {% elif delivery_cost == 60 %}
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="location" id="inside_dhaka" value="1" checked>
                      <label class="form-check-label" for="exampleRadios1">
                        Inside Dhaka City
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="location" id="outside_dhaka" value="0">
                      <label class="form-check-label" for="exampleRadios2">
                        Outside Dhaka City
                      </label>
                    </div>
                    {% elif delivery_cost == 120 %}
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="location" id="inside_dhaka" value="1">
                      <label class="form-check-label" for="exampleRadios1">
                        Inside Dhaka City
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="location" id="outside_dhaka" value="0" checked>
                      <label class="form-check-label" for="exampleRadios2">
                        Outside Dhaka City
                      </label>
                    </div>
                    {%endif%}
                  </td>
                  <td class="text-right">
                    <button class="btn btn-primary" type="submit"> Add</button>
                  </td>
                </form>
              </tr>




            </tbody>
          </table>
        </div>

        <!-- Discount  -->
        {% if discount < 0 %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>Invalid!</strong> The coupon you added is unavailable.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Discount</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>

              <tr>
                <form action="{% url 'cart' %}" class="discount" method='POST'> {% csrf_token %}

                  <td>
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Discount (If Any)" name="discount">
                    </div>
                  </td>

                  <td class="text-right">
                    <button class="btn btn-primary" type="submit"> Add</button>
                  </td>
                </form>
              </tr>




            </tbody>
          </table>
        </div>

        {% elif discount > 0 %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>Voila!</strong> Your discount has been added.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Discount</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>

              <tr>
                <form action="{% url 'cart' %}" class="discount" method='POST'> {% csrf_token %}

                  <td>
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Discount (If Any)" name="discount"
                        value="{{discount_code}}">
                    </div>
                  </td>

                  <td class="text-right">
                    <button class="btn btn-primary" type="submit"> Add</button>
                  </td>
                </form>
              </tr>




            </tbody>
          </table>
        </div>
        {% else %}
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Discount</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>

              <tr>
                <form action="{% url 'cart' %}" class="discount" method='POST'> {% csrf_token %}

                  <td>
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Discount (If Any)" name="discount">
                    </div>
                  </td>

                  <td class="text-right">
                    <button class="btn btn-primary" type="submit"> Add</button>
                  </td>
                </form>
              </tr>




            </tbody>
          </table>
        </div>
        {% endif %}






      </aside> <!-- col.// -->
      <aside class="col-lg-3">

        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">৳{{total}}</dd>
            </dl>
            {% if discount >= 0 %}
            <dl class="dlist-align">
              <dt>Discount:</dt>
              <dd class="text-right"> ৳{{discount}}</dd>
            </dl>
            {% endif %}
            <dl class="dlist-align">
              <dt>Delivery Cost:</dt>
              <dd class="text-right"> ৳{{delivery_cost}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Total:</dt>
              <dd class="text-right text-dark b"><strong>৳{{grand_total}}</strong></dd>
            </dl>
            <hr>
            <p class="text-center mb-3">
              <img src="{% static 'shop/images/misc/payments.png' %}" height="26">
            </p>
            <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
            <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
          </div> <!-- card-body.// -->
        </div> <!-- card.// -->

      </aside> <!-- col.// -->


    </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->

  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

shop/templates/shop/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>MagicEpic</p>
</body>
</html>

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %} {% load static %} {% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <a href="#"><img src="{{single_product.image.url}}" /></a>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{single_product.product_name}}</h2>

              <div class="mb-3">
                <var class="price h4">৳{{single_product.price}}</var>
              </div>

              <p>{{single_product.description}}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Varient</h6>
                  <select name="varient" class="form-control" required>
                    <!-- _set.all brings out all data from variation  -->
                    <!-- we are using _set.varient because 
                      we need all data of varient. 
                      not anything else, 
                      such as if there were any other 
                      section named "color", the sections of color also come here if all were there.  -->
                    <option value="" disabled selected>Select</option>
                    {% for i in single_product.variation_set.all %}
                    <option value="{{i.variation_value | lower }}">{{i.variation_value | capfirst}}</option> 
                    <!-- capfirst is for first letter will be capital -->
                    <!-- lower is for keeping everything in lower letter  -->
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %}
              <h5 class="text-danger">Out of Stock</h5>
              {% else %}
              <button
                
                class="btn btn-primary"
                type="submit"
              >
                <span class="text">Add to cart</span>
                <i class="fas fa-shopping-cart"></i>
              </button>
              {% endif %} 
            </article>
            <!-- product-info-aside .// -->
          </form>
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        <header class="section-heading">
          <h3>Customer Reviews</h3>
        </header>

        <article class="box mb-3">
          <div class="icontext w-100">
            <img
              src="./images/avatars/avatar1.jpg"
              class="img-xs icon rounded-circle"
            />
            <div class="text">
              <span class="date text-muted float-md-right">24.04.2020 </span>
              <h6 class="mb-1">Mike John</h6>
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <p>
              Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing
              elit, sed do eiusmod tempor incididunt ut labore et dolore magna
              aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
              laboris nisi ut aliquip
            </p>
          </div>
        </article>
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}